# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='frozen_capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='冻结资金'),
        ),
    ]
